### ISSUE TITLE
problem at making 2

### ISSUE THREAD

**Issue by yeonji1** [msoos/grainofsalt#3]
Dear Mr. soo. this is Yeonji.
Hello I've sent mail to you 4days ago about 'make problem', and I also tried 'make VERBOSE=1'.
But I still have problem, so I leave a Issues in here. 
what I did is
  1.  installed prerequisites packages:
      cmake -  3.5.1(version)
      bignum library - gmp 2:6.1.0+dfsg-2(version)
      boost library - 1. 58 .0
      zlib library -  1.2.11

  2.  installed in Build folder
       cmake ../  
       make
       under error is occued

I attach screenshot of error page and cmake,make command.
Thank you!!

![screenshot from 2018-05-08 09-18-59](https://user-images.githubusercontent.com/39071410/39731256-87b55aee-52a1-11e8-95d2-215c6af38e4d.png)
[CMakeLists.txt](https://github.com/msoos/grainofsalt/files/1981868/CMakeLists.txt)
[CMakeCache.txt](https://github.com/msoos/grainofsalt/files/1981870/CMakeCache.txt)
[makefile.txt](https://github.com/msoos/grainofsalt/files/1981876/makefile.txt)

**Comment by msoos** [comment]
Yep, espresso is too old. Just remove "restrict" from there and anywhere where it causes an error. Please create a pull request as well. Also, please do NOT create screenshots -- copy-paste the full error instead.

**Comment by yeonji1** [comment]
Oh. I got it. Here is Full error message file.
[error message.txt](https://github.com/msoos/grainofsalt/files/1982301/error.message.txt)

**Comment by msoos** [comment]
Oh, I remember. Just rename the variable "restrict" to something else! like restrict_1. Please create a pull request once you have fixed it! Thanks!

**Comment by yeonji1** [comment]
The matter of "restrict" is cleared. but it told me there's no "bestbits.cpp.o" file.
Actually, there's really no "bestbits.cpp.o" file, when I searched the directory 'generator/CMakeFiles/grainofsalt.dir/'

[error message (2).txt](https://github.com/msoos/grainofsalt/files/1982424/error.message.2.txt)

**Comment by msoos** [comment]
I have now updated the system. Please delete all of the directory, then:

```
rm -rf grainofsalt
git clone https://github.com/msoos/grainofsalt
cd grainofsalt
mkdir build
cd build
cmake ..
make
```

The bestbits.cpp file is now in there. Good luck!
