### ISSUE TITLE
IDEA: CNF conversion to FPGA based solving

### ISSUE THREAD

**Issue by tinylabs** [msoos/grainofsalt#5]
Hello,
I saw you had a post on potentially implemented a SAT solver for arbitrary CNFs on an FPGA. I'm wondering if you have any insights into creating a tool to convert a specific CNF to fixed logic that is well suited for an FPGA?
Specifically, I implemented a solver for Crypto1 using your tools here: https://github.com/tinylabs/crypto-sat-solve.git
We happen to have an FPGA available and I'm curious what sort of performance could be gained by moving it to the FPGA.

**Comment by msoos** [comment]
Hi,

This sounds too much like someone being in the business to try to do illegal things. I can't support this in any way shape or form. I would have strongly advised against releasing that tool. 

It's one thing to demonstrate that a system is weak, to push the system designers to fix the flaws and to make sure they don't make the same mistake again. That acting within the public interest, to protect everyone. It's an _entirely_ different thing to publicly release a tool that can make it extremely simple to copy keys, and hence potentially commit crime.

I'm closing this issue.

**Comment by tinylabs** [comment]
Releasing that tool in my view is purely academic as it doesn't improve on the state of the art for breaking mifare. I understand where you're coming from though. Apologies.
